SELECT * FROM fauna2.punto;
USE fauna2;
SELECT p.NOMBRE, t.CLASE, SUM(m.ABUND_ABS) ABUNDANCIAS   
FROM muestreo m INNER JOIN punto p
ON PUNTO_MUEST = ID_MUES_PT
INNER JOIN taxonomia t ON m.SP = t.ESPECIE
GROUP BY p.NOMBRE, t.CLASE WITH ROLLUP
ORDER BY p.NOMBRE;

SELECT p.NOMBRE, t.ESPECIE, SUM(m.ABUND_ABS)   
FROM muestreo m INNER JOIN punto p
ON PUNTO_MUEST = ID_MUES_PT
INNER JOIN taxonomia t ON m.SP = t.ESPECIE
GROUP BY p.NOMBRE, t.ESPECIE WITH ROLLUP
ORDER BY p.NOMBRE;